services:
  db:
    image: mariadb
    restart: always
    networks:
      - app_network
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    expose:
      - 3306
      - 33060

  bs:
    restart: always
    build:
      context: bs
      target: builder
    hostname: bs
    stop_signal: SIGINT
    networks:
      - app_network
    ports:
      - "8001:8000"
    depends_on:
      - db

  proxy:
    restart: always
    build: nginx
    ports:
      - "8080:8080"
    networks:
      - app_network
    depends_on:
      - bs

networks:
  app_network:
    driver: bridge
